Shop\Category:
  type: entity
  table: categories
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
    description:
      type: text
  manyToMany:
      products:
        targetEntity: Product
        mappedBy: products
Shop\Product2:
  type: entity
  table: products
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
    price:
      type: integer
      nullable: TRUE