Test\Product_Store_CustomerGroup:
    type: entity
    table: test_product_store_customergroup
    fields:
        price:
            type: integer
    id:
        product:
            associationKey: true
        store:
            type: string
            generator: { strategy: NONE }
        customerGroup:
            type: string
            generator: { strategy: NONE }
    manyToOne:
        product:
            targetEntity: Test\Product
            inversedBy: scope_store_customergroups
